version: '3'
services:
  tm-idp:
    build:
      context: .
      dockerfile: Dockerfile-tendermint
    volumes:
      - ./docker-config/tendermint/IdP:/tendermint
    ports:
      - 45000:45000
      - 47000:47000
    networks:
      - ndid
    depends_on:
      - abci-idp
  tm-rp:
    build:
      context: .
      dockerfile: Dockerfile-tendermint
    volumes:
      - ./docker-config/tendermint/RP:/tendermint
    ports:
      - 45001:45001
      - 47001:47001
    networks:
      - ndid
    depends_on:
      - abci-rp
  abci-idp:
    build:
      context: .
      dockerfile: Dockerfile-abci
    environment:
      CALLBACK_URI: http://localhost:3001/callback
    networks:
      - ndid
    command: ["/abci-server","tcp://0.0.0.0:46000"]
  abci-rp:
    build:
      context: .
      dockerfile: Dockerfile-abci
    environment:
      CALLBACK_URI: http://localhost:3002/callback
    networks:
      - ndid
    command: ["/abci-server","tcp://0.0.0.0:46001"]
networks:
  ndid:
    driver: bridge